export const ALL_FOOD_REQUEST = "ALL_FOOD_REQUEST";
export const ALL_FOOD_SUCCESS = "ALL_FOOD_SUCCESS";
export const ALL_FOOD_FAIL = "ALL_FOOD_FAIL";

export const ADMIN_FOOD_REQUEST = "ADMIN_FOOD_REQUEST";
export const ADMIN_FOOD_SUCCESS = "ADMIN_FOOD_SUCCESS";
export const ADMIN_FOOD_FAIL = "ADMIN_FOOD_FAIL";

export const NEW_FOOD_REQUEST = "NEW_FOOD_REQUEST";
export const NEW_FOOD_SUCCESS = "NEW_FOOD_SUCCESS";
export const NEW_FOOD_RESET = "NEW_FOOD_RESET";
export const NEW_FOOD_FAIL = "NEW_FOOD_FAIL";

export const UPDATE_FOOD_REQUEST = "UPDATE_FOOD_REQUEST";
export const UPDATE_FOOD_SUCCESS = "UPDATE_FOOD_SUCCESS";
export const UPDATE_FOOD_RESET = "UPDATE_FOOD_RESET";
export const UPDATE_FOOD_FAIL = "UPDATE_FOOD_FAIL";

export const DELETE_FOOD_REQUEST = "DELETE_FOOD_REQUEST";
export const DELETE_FOOD_SUCCESS = "DELETE_FOOD_SUCCESS";
export const DELETE_FOOD_RESET = "DELETE_FOOD_RESET";
export const DELETE_FOOD_FAIL = "DELETE_FOOD_FAIL";

export const FOOD_DETAILS_REQUEST = "FOOD_DETAILS_REQUEST";
export const FOOD_DETAILS_SUCCESS = "FOOD_DETAILS_SUCCESS";
export const FOOD_DETAILS_FAIL = "FOOD_DETAILS_FAIL";

export const NEW_COMMENT_REQUEST = "NEW_COMMENT_REQUEST";
export const NEW_COMMENT_SUCCESS = "NEW_COMMENT_SUCCESS";
export const NEW_COMMENT_RESET = "NEW_COMMENT_RESET";
export const NEW_COMMENT_FAIL = "NEW_COMMENT_FAIL";

export const ALL_COMMENT_REQUEST = "ALL_COMMENT_REQUEST";
export const ALL_COMMENT_SUCCESS = "ALL_COMMENT_SUCCESS";
export const ALL_COMMENT_FAIL = "ALL_COMMENT_FAIL";

export const ACCEPT_COMMENT_REQUEST = "ACCEPT_COMMENT_REQUEST";
export const ACCEPT_COMMENT_SUCCESS = "ACCEPT_COMMENT_SUCCESS";
export const ACCEPT_COMMENT_RESET = "ACCEPT_COMMENT_RESET";
export const ACCEPT_COMMENT_FAIL = "ACCEPT_COMMENT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
